# Generated by Django 5.0.8 on 2025-07-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoucron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sommet',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sommet',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='arc',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
